import React from "react";
import { Metadata } from "next";
import LeftBar from "@/components/common/LeftBar";
import Footer from "@/components/common/Footer";
import Navbar from "@/components/common/Navbar";

export const metadata: Metadata = {
	title: "BetMaster",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const style = { flex: 1, marginRight: "20px" };

	return (
		<html lang="en">
			<body>
				<div style={{ display: "flex" }}>
					<LeftBar style={style} />
					<div style={{ flex: 3 }}>
						<Navbar />
						{children}
					</div>
				</div>
				<Footer />
			</body>
		</html>
	);
}
