import { Metadata } from "next/document";
import "./globals.css";
import LeftBar from "@/components/base/Leftbar";
import Footer from "@/components/base/Footer";
import Header from "@/components/base/Header";

export const metadata: Metadata = {
	title: "BetMaster",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Header />
				<div className="flex">
					<LeftBar />
					<div className="flex-1">{children}</div>
				</div>
				<Footer />
			</body>
		</html>
	);
}
